export const ADD_TO_HEART = "ADD_TO_HEART"
export const REMOVE_FROM_HEART = "REMOVE_FROM_HEART"
export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART"
export const DECREMENT_FROM_CART = "DECREMENT_FROM_CART"
